[ llGetExperienceErrorMessage(-2)
, llGetExperienceErrorMessage(-1)
, llGetExperienceErrorMessage( 0)
, llGetExperienceErrorMessage( 1)
, llGetExperienceErrorMessage( 2)
, llGetExperienceErrorMessage( 3)
, llGetExperienceErrorMessage( 4)
, llGetExperienceErrorMessage( 5)
, llGetExperienceErrorMessage( 6)
, llGetExperienceErrorMessage( 7)
, llGetExperienceErrorMessage( 8)
, llGetExperienceErrorMessage( 9)
, llGetExperienceErrorMessage(10)
, llGetExperienceErrorMessage(11)
, llGetExperienceErrorMessage(12)
, llGetExperienceErrorMessage(13)
, llGetExperienceErrorMessage(14)
, llGetExperienceErrorMessage(15)
, llGetExperienceErrorMessage(16)
, llGetExperienceErrorMessage(17)
, llGetExperienceErrorMessage(18)
, llGetExperienceErrorMessage(19)
, llGetExperienceErrorMessage(20)
, llGetExperienceErrorMessage(21)
, llGetExperienceErrorMessage(22)
, llGetExperienceErrorMessage(23)
, llGetExperienceErrorMessage(24)
, llGetExperienceErrorMessage(25)
, llGetExperienceErrorMessage(26)
, llGetExperienceErrorMessage(27)
, llGetExperienceErrorMessage(28)
, llGetExperienceErrorMessage(29)
, llGetExperienceErrorMessage(30)
]