[ llComputeHash("", "md5")
, llComputeHash("", "sha1")
, llComputeHash("", "md5_sha1")
, llComputeHash("", "sha224")
, llComputeHash("", "sha256")
, llComputeHash("", "sha384")
, llComputeHash("", "sha512")
, llComputeHash("Ħ", "md5")
, llComputeHash("Ħ", "sha1")
, llComputeHash("Ħ", "md5_sha1")
, llComputeHash("Ħ", "sha224")
, llComputeHash("Ħ", "sha256")
, llComputeHash("Ħ", "sha384")
, llComputeHash("Ħ", "sha512")
]